name: private-isu
services:
  nginx:
    image: nginx:1.24
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ./public:/public
    ports:
      - "8080:80"
    networks:
      - my_network

  app:
    # Go実装の場合は golang/ PHP実装の場合は php/
    build: golang/
    environment:
      ISUCONP_DB_HOST: mysql
      ISUCONP_DB_PORT: 3306
      ISUCONP_DB_USER: root
      ISUCONP_DB_PASSWORD: root
      ISUCONP_DB_NAME: isuconp
      ISUCONP_MEMCACHED_ADDRESS: memcached:11211
    networks:
      - my_network
    volumes:
      - ./public:/home/public
    init: true
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1g

  mysql:
    image: mysql:8.0
    environment:
      #- "TZ=Asia/Tokyo"
      - "MYSQL_ROOT_HOST=%"
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - mysql:/var/lib/mysql
      - ./etc/my.cnf:/etc/my.cnf
      - ./sql:/docker-entrypoint-initdb.d
      - ./logs/mysql:/var/log/mysql
    ports:
      - "13306:3306"
    networks:
      - my_network
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1g

  memcached:
    image: memcached:1.6
    networks:
      - my_network

volumes:
  mysql:

networks:
  my_network:
